#В этой таблице мы записываем расшифровку для каждого пункта из таблицы Decoding_Competency
CREATE TABLE Decoding_Competency_Full (
SPECIALTYCODE INT NOT NULL,
COMPETENCE1 LONGTEXT NOT NULL,
COMPETENCE2 LONGTEXT NOT NULL,
COMPETENCE3 LONGTEXT NOT NULL,
COMPETENCE4 LONGTEXT NOT NULL,
COMPETENCE5 LONGTEXT NOT NULL,
COMPETENCE6 LONGTEXT,
COMPETENCE7 LONGTEXT,
COMPETENCE8 LONGTEXT,
COMPETENCE9 LONGTEXT,
COMPETENCE10 LONGTEXT,
COMPETENCE11 LONGTEXT,
COMPETENCE12 LONGTEXT,
COMPETENCE13 LONGTEXT,
COMPETENCE14 LONGTEXT,
COMPETENCE15 LONGTEXT,
FOREIGN KEY (SPECIALTYCODE) REFERENCES Specialty_Code (SPECIALTYCODE)
);