USE RESUME;

CREATE TABLE Specialty_Code (
SPECIALTYCODE INT NOT NULL AUTO_INCREMENT,
SPECIALTYNAME VARCHAR(255) NOT NULL,
PRIMARY KEY (SPECIALTYCODE)
);

#Расшифровка компетенций для внесения в резюме
CREATE TABLE Decoding_Competency_Full (
SPECIALTYCODE INT NOT NULL,
COMPETENCE1 TEXT NOT NULL,
COMPETENCE2 TEXT NOT NULL,
COMPETENCE3 TEXT NOT NULL,
COMPETENCE4 TEXT NOT NULL,
COMPETENCE5 TEXT NOT NULL,
COMPETENCE6 TEXT,
COMPETENCE7 TEXT,
COMPETENCE8 TEXT,
COMPETENCE9 TEXT,
COMPETENCE10 TEXT,
COMPETENCE11 TEXT,
COMPETENCE12 TEXT,
COMPETENCE13 TEXT,
COMPETENCE14 TEXT,
COMPETENCE15 TEXT,
FOREIGN KEY (SPECIALTYCODE) REFERENCES Specialty_Code (SPECIALTYCODE)
);
#Для хранения значений для чекбоксов
CREATE TABLE Decoding_Competency (
SPECIALTYCODE INT NOT NULL,
COMPETENCE1 TEXT NOT NULL,
COMPETENCE2 TEXT NOT NULL,
COMPETENCE3 TEXT NOT NULL,
COMPETENCE4 TEXT NOT NULL,
COMPETENCE5 TEXT NOT NULL,
COMPETENCE6 TEXT,
COMPETENCE7 TEXT,
COMPETENCE8 TEXT,
COMPETENCE9 TEXT,
COMPETENCE10 TEXT,
COMPETENCE11 TEXT,
COMPETENCE12 TEXT,
COMPETENCE13 TEXT,
COMPETENCE14 TEXT,
COMPETENCE15 TEXT,
FOREIGN KEY (SPECIALTYCODE) REFERENCES Specialty_Code (SPECIALTYCODE)
);

CREATE TABLE Student(
ID INT NOT NULL AUTO_INCREMENT,
STUDENTNAME VARCHAR(255) NOT NULL,
DATEOFBIRTH DATETIME NOT NULL,
GROUPNUMBER VARCHAR(14) NOT NULL,
SPECIALTYCODE INT NOT NULL,
TELEPHONENUMBER VARCHAR(16) NOT NULL,
EMAILADDRESS VARCHAR(32) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (SPECIALTYCODE) REFERENCES Specialty_Code (SPECIALTYCODE)
);


#Для хранения данных о компетенциях студента
CREATE TABLE Student_Competencies (
ID INT NOT NULL,
COMPETENCE1 BIT NOT NULL,
COMPETENCE2 BIT NOT NULL,
COMPETENCE3 BIT NOT NULL,
COMPETENCE4 BIT NOT NULL,
COMPETENCE5 BIT NOT NULL,
COMPETENCE6 BIT,
COMPETENCE7 BIT,
COMPETENCE8 BIT,
COMPETENCE9 BIT,
COMPETENCE10 BIT,
COMPETENCE11 BIT,
COMPETENCE12 BIT,
COMPETENCE13 BIT,
COMPETENCE14 BIT,
COMPETENCE15 BIT,
FOREIGN KEY (ID) REFERENCES Student (ID)
);

CREATE TABLE Student_Additional_Info (
ID INT NOT NULL,
ADDITIONALINFO LONGTEXT NOT NULL,
FOREIGN KEY (ID) REFERENCES Student (ID)
);

CREATE TABLE Student_Photo (
ID INT NOT NULL,
PHOTO BLOB NOT NULL,
PRIMARY KEY (ID)
);

