CREATE TABLE Student_Competencies (
ID INT NOT NULL,
COMPETENCE1 BIT NOT NULL,
COMPETENCE2 BIT NOT NULL,
COMPETENCE3 BIT NOT NULL,
COMPETENCE4 BIT NOT NULL,
COMPETENCE5 BIT NOT NULL,
COMPETENCE6 BIT,
COMPETENCE7 BIT,
COMPETENCE8 BIT,
COMPETENCE9 BIT,
COMPETENCE10 BIT,
COMPETENCE11 BIT,
COMPETENCE12 BIT,
COMPETENCE13 BIT,
COMPETENCE14 BIT,
COMPETENCE15 BIT,
FOREIGN KEY (ID) REFERENCES Student (ID)
);