USE RESUME;
CREATE TABLE Student_Education (
ID INT NOT NULL,
ESTABLISHMENT VARCHAR(255) NOT NULL,
FACULTY VARCHAR(255) NOT NULL,
FORMOFSTUDY VARCHAR(255) NOT NULL,
YEAROFENDING VARCHAR(255) NOT NULL,
FOREIGN KEY (ID) REFERENCES Student (ID)
);