USE RESUME;
CREATE TABLE Student_Additional_Info (
ID INT NOT NULL,
ADDITIONALINFO VARCHAR(255) NOT NULL,
FOREIGNLANGUAGE VARCHAR(255) NOT NULL,
DRIVERLICENSE VARCHAR(255) NOT NULL,
ADDITIONALCOMPETENCIES VARCHAR(255) NOT NULL,
SOCIALNETWORK VARCHAR(255) NOT NULL,
FOREIGN KEY (ID) REFERENCES Student (ID)
);